services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Portrino\PxValidation\:
        resource: '../Classes/*'
        exclude: '../Classes/Reflection/*'
